name: Publish Python Package on Tag

on:
  push:
    tags:
      - "v*.*.*" # Triggers only on version tags like v0.1.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure full history for versioning

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine bump2version

      - name: Extract version from tag
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update version in pyproject.toml
        run: |
          bump2version --new-version ${{ steps.get_version.outputs.version }} patch --allow-dirty --no-tag

      - name: Commit updated version
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "ci: bump version to ${{ steps.get_version.outputs.version }} [skip ci]"
          git push

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: python -m twine upload dist/*
