name: Upload Python Package to PyPI

on:
  push:
    tags:
      - "v*.*.*" # Match version tags like v0.1.0, v1.2.3

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required to access tags

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install build twine bump-my-version

      - name: Get tag version
        id: get_tag
        run: |
          echo "tag=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Bump to tag version
        run: bump-my-version set ${{ steps.get_tag.outputs.tag }} --yes

      - name: Build package
        run: |
          rm -rf dist/
          python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload dist/*
